name: uploadToS3
on:
  schedule:
     # Run every 10 minutes ('*/10 * * * *')
     # Run every day at midnight +10 mins
    - cron:  '10 0 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete  --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.DESTINATION_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
