# .github/workflows/xeno-syncfork.yml

name: Merge upstream branches
on:
  schedule:
     # Run every 10 minutes ('*/10 * * * *')
     # Run every day at midnight
    - cron:  '0 0 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'XenoM0rph97'
          git config --global user.email 'XenoM0rph97@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/CVEProject/cvelistV5.git
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
